version: "3.9"

name: lifi-indexer

services:
  # app:
  #   container_name: lifi-express
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_NAME: ${DB_NAME}
  #     DATABASE_USER: ${DB_USER}
  #     DATABASE_PASS: ${DB_PASS}
  #     DATABASE_URI: ${DB_HOST}
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME}